[package]
name = "ordinalsync"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.18.0"

[dev-dependencies]
snforge_std = { version = "0.44.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
